/**
 * This file contains all the functions that are not generated by MCC
*/

/* 

*/

#ifndef FUNCTIONS_H
#define FUNCTIONS_H

/*
 * Global Variable and Constant definitions
 * 
 */
#include "mcc_generated_files/system/system.h"

typedef struct
{
    uint16_t baseTimerCnt, timerCnt, delayTimeCounter;
    uint16_t timerCnt_01ms, timerCnt_05ms, timerCnt_10ms, timerCnt_50ms;
    uint16_t timerCnt_100ms;
    uint8_t  timerFlags;
    
    uint8_t     txBufferIndex, rxBufferIndex, bytesToRx, bytesToTx;
    uint8_t     txBuffer[32], rxBuffer[16];
    uint8_t     UART1Flags;
    
    uint8_t spiRxBuffer[16], spiTxBuffer[16];
    uint8_t spiRxIndex, spiTxIndex, spiBufferSize;
    
    uint8_t tagSN[5];

} globalVariableType;

extern globalVariableType gv, *pgv;

//-- UART functions
void UART1_SendMsgPrepare(uint8_t bytes);
void UART1_SendMessage(void);
void UART1_RxMessageProcess(void);

void shortDelay(uint16_t time);     // delay a number of Fosc cycles. Not accurate
void myDelay(uint16_t delayTime);    // delay Time in ms. using timer1
void timedAppTasks(void);

void timedEvents_01ms(void);
void timedEvents_05ms(void);
void timedEvents_10ms(void);
void timedEvents_50ms(void);
void timedEvents_100ms(void);

//-- SPI functions
void spi_read(void);
void BMA400_CS_Init(void);
uint8_t BMA400_ReadID(void);
void BMA400_ReadRegisters(uint8_t startAddress, uint8_t *data, uint8_t length);
void BMA400_WriteRegister(uint8_t regAddress, uint8_t data);

//- UART variables
#define MSG_HEADER_OUT  0xA5        // Message sent to PC
#define MSG_HEADER_IN   0x5A        // Message received 
#define MSG_TYPE_TAG    0x01
#define MSG_TYPE_SN     0x02
#define MSG_TYPE_BLOCK_DATA   0x03

#define fUART1_RxReady   0x01
#define fUART1_TxReady   0x02
#define fUART1_RxMsgReady   0x04
#define fUART1_Txing    0x08

// Timer variables
#define ftimer_01ms  0x01
#define ftimer_05ms  0x02
#define ftimer_10ms  0x04
#define ftimer_50ms  0x08
#define ftimer_100ms  0x10


// SPI interface
#define SPI1_DUMMY_DATA_BMA400 0x00
//#define BMA400_CS_PIN PORTCbits.RC3 
//#define BMA400_PWR_PIN PORTCbits.RC6

#define BMA400_ID_REGISTER 0x00 // ID register address
#define BMA400_ID_READ (BMA400_ID_REGISTER | 0x80) // Read operation (MSB set)

#endif //FUNCTIONS_H

/**
 End of File
*/


