/*
© Namawell 
 * RFID demo project

 * This file contains all the functions that are not generated by the MCC
*/
#include "rfid.h"
#include "functions.h"
#include "mcc_generated_files/spi_host/spi1.h"
#include "mcc_generated_files/system/system.h"
/*
 functions list:
 * 
 * 
*/
#include <xc.h>
#include <stdbool.h>
#include "math.h"

uint8_t tagType[2];
uint8_t serNum[5];  //Serial Number of the Tag
uint8_t sectorKey[6] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};  // Default key for authentication
uint8_t tagRxData[BLOCK_SIZE];
uint8_t tagTxData[BLOCK_SIZE]; 

uint8_t tagStatus, tagByteLength;

//This is the tag detection interrupt
void IO_RC5_Int_CallBack(void)
{
    /* Interrupt for tag closing does not work. The reader does not generate the IRQ signal 
     when a tag is within the range. Keep using polling method (50ms interval)*/
    
    /*
    uint8_t myStr[16], i, tagStatus;
    uint8_t irqReg;
        // Check if the interrupt came from RC5 (INT pin)
    if (PORTCbits.RC5 == 0) 
    {
        irqReg = PCD_ReadRegister(ComIrqReg);
    
    // Check if the IdleIEn interrupt is set
        if (irqReg & 0x10) 
        {
        // Call MFRC522_Request inside ISR
                // Handle the interrupt (e.g., read the tag ID)
            tagStatus = MFRC522_DetectTag();
            if (tagStatus = MI_OK)
            {
                // A tag is detected, and its serial number (ID) is read
                // Process the tag data here
                // Send the SN to PC
                pgv->txBuffer[0] = MSG_HEADER_OUT;    
                pgv->txBuffer[1] = MSG_TYPE_SN;    
                pgv->txBuffer[2] = serNum[0];    
                pgv->txBuffer[3] = serNum[1];    
                pgv->txBuffer[4] = serNum[2];    
                pgv->txBuffer[5] = serNum[3];    

                UART1_SendMsgPrepare(6);
            }
        // Process tagType to determine tag presence or type
        }
    
    // Clear the interrupt flag after processing
        PCD_WriteRegister(ComIrqReg, irqReg);    
    } 
*/   
}
/*
 * Function Name: InitMFRC522
 * Description: Initialize RC522
 * Input: None
 * Return value: None
*/
void MFRC522_Init(void)
{
    
  MFRC522_RESET_PIN = 0;
  myDelay(10);  // delay 10ms   
  MFRC522_RESET_PIN = 1;
  //NRSTPD = 1;// reset pin high
//Open SPI1
  
    if (!SPI1_Open(0))
    {
        LATDbits.LATD10 = 0;     // turn on Led
    }
    
  
  MFRC522_Reset();
  myDelay(10);

  //Timer: TPrescaler*TreloadVal/6.78MHz = 24ms
  PCD_WriteRegister(TModeReg, 0x8D);                //Tauto=1; f(Timer) = 6.78MHz/TPreScaler
  PCD_WriteRegister(TPrescalerReg, 0x3E);        //TModeReg[3..0] + TPrescalerReg
  PCD_WriteRegister(TReloadRegL, 30);
  PCD_WriteRegister(TReloadRegH, 0);

  PCD_WriteRegister(TxASKReg, 0x40);                //100%ASK
  PCD_WriteRegister(ModeReg, 0x3D);                //CRC Initial value 0x6363        ???
  
    // Enable RX interrupt
 MFRC522_EnableInterrupt();
  

  //ClearBitMask(Status2Reg, 0x08);                //MFCrypto1On=0
  //Write_MFRC522(RxSelReg, 0x86);                //RxWait = RxSelReg[5..0]
  //Write_MFRC522(RFCfgReg, 0x7F);                   //RxGain = 48dB

  AntennaOn();                //Open the antenna
}

uint8_t MFRC522_DetectTag(void)
{
    uint8_t result, i;
    
    result = MI_NOTAGERR;
    if (MFRC522_Request(PICC_REQIDL, tagType) == 0) 
        {
            if (MFRC522_Anticoll(serNum) == 0) 
            {
                // A tag is detected, and its serial number (ID) is read
                for (i=0; i<5; i++)
                {
                    pgv->tagSN[i] = serNum[i]; // Transfer SN
                }
                result = MI_OK;
            }
        } 
    return result;
}

void MFRC522_EnableInterrupt(void) 
{
    // Enable Idle interrupt and Timer interrupt
    PCD_WriteRegister(ComIEnReg, (1 << 1) | (1 << 7)); // IdleIEn = 1, TimerIEn = 1
    // Enable LoAlertIEn and HiAlertIEn interrupts
    PCD_WriteRegister(DivIEnReg, (1 << 2) | (1 << 3)); // HiAlertIEn = 1, LoAlertIEn = 1
    // Clear the interrupt request flags
    PCD_WriteRegister(ComIrqReg, 0x7F);  // Clear all flags
    // Enable IRQ pin output (optional)
    PCD_WriteRegister(ComIrqReg, 0x80);  // IRQ pin output enabled
}



void PCD_WriteRegister(	uint8_t reg, uint8_t data ) 
{
    uint8_t address = (reg << 1) & 0x7E;
    // Set the chip select line low to start communication
    // Select the sensor (pull CS low)
    LATCbits.LATC3 = 0; // Select the sensor (CS low)
    
    // Send the register address with write operation (MSB = 0)
    SPI1_ByteExchange(address);
    
    // Send the data byte to be written to the register
    SPI1_ByteExchange(data);
    
    // Deselect the sensor (pull CS high)
    LATCbits.LATC3 = 1; //
    shortDelay(100);    // approximate delay Fosc cycles
}

uint8_t PCD_ReadRegister( uint8_t reg ) 
{
    
    uint8_t id;
    uint8_t address = ((reg << 1) & 0x7E) | 0x80;
    LATCbits.LATC3 = 0; // Select the sensor (CS low)

    SPI1_ByteExchange(address); // Send read command
    id = SPI1_ByteExchange(0x00); // Send dummy data for clocks, Read data
    
    LATCbits.LATC3 = 1; // Deselect the sensor (CS high)
    shortDelay(100);    // approximate delay Fosc cycles

    return id;
}

//void PCD_ReadRegister( uint8_t reg, uint8_t *values , uint8_t count) 
//{
//    ///< The register to read from. One of the PCD_Register enums.
//    ///< Byte array to store the values in.
//    ///< The number of bytes to read
//    I2C1_ReadDataBlock(MFRC552, reg, *values, count);
//}


/*
 * Function Name: SetBitMask
 * Description: Set RC522 register bit
 * Input parameters: reg - register address; mask - set value
 * Return value: None
 */
void SetBitMask(uint8_t reg, uint8_t mask)
{
  uint8_t tmp;
  tmp = PCD_ReadRegister(reg);
  PCD_WriteRegister(reg, tmp | mask);  // set bit mask
}


/*
 * Function Name: ClearBitMask
 * Description: clear RC522 register bit
 * Input parameters: reg - register address; mask - clear bit value
 * Return value: None
*/
void ClearBitMask(uint8_t reg, uint8_t mask)
{
  uint8_t tmp;
  tmp = PCD_ReadRegister(reg);
  PCD_WriteRegister(reg, tmp & (~mask));  // clear bit mask
}


/*
 * Function Name: AntennaOn
 * Description: Open antennas, each time you start or shut down the natural barrier between the transmitter should be at least 1ms interval
 * Input: None
 * Return value: None
 */
void AntennaOn(void)
  {
  uint8_t temp;
  temp = PCD_ReadRegister(TxControlReg);
  if (!(temp & 0x03))
  {
    SetBitMask(TxControlReg, 0x03);
  }
}


/*
  * Function Name: AntennaOff
  * Description: Close antennas, each time you start or shut down the natural barrier between the transmitter should be at least 1ms interval
  * Input: None
  * Return value: None
 */
void AntennaOff(void)
{
  ClearBitMask(TxControlReg, 0x03);
}


/*
 * Function Name: ResetMFRC522
 * Description: Reset RC522
 * Input: None
 * Return value: None
 */
void MFRC522_Reset(void)
{
  PCD_WriteRegister(CommandReg, PCD_RESETPHASE);
}


/*
 * Function Name: MFRC522_Request
 * Description: Find cards, read the card type number
 * Input parameters: reqMode - find cards way
 *                         TagType - Return Card Type
 *                                0x4400 = Mifare_UltraLight
 *                                0x0400 = Mifare_One(S50)
 *                                0x0200 = Mifare_One(S70)
 *                                0x0800 = Mifare_Pro(X)
 *                                0x4403 = Mifare_DESFire
 * Return value: the successful return MI_OK
 */
uint8_t MFRC522_Request(uint8_t reqMode, uint8_t *TagType)
{
  uint8_t status;
  uint8_t backBits;                        //The received data bits
  uint8_t buf[2];

  PCD_WriteRegister(BitFramingReg, 0x07);                //TxLastBists = BitFramingReg[2..0]        ???

  buf[0] = reqMode;
  status = MFRC522_ToCard(PCD_TRANSCEIVE, buf, 1, TagType, &backBits);

  return status;                                      //returns tag type that includes FIFO data that was read
}


/*
 * Function Name: MFRC522_ToCard
 * Description: RC522 and ISO14443 card communication
 * Input Parameters: command - MF522 command word,
 *                         sendData--RC522 sent to the card by the data
 *                         sendLen--Length of data sent
 *                         backData--Received the card returns data,
 *                         backLen--Return data bit length
 * Return value: the successful return MI_OK
 */
uint8_t MFRC522_ToCard(uint8_t command, uint8_t *sendData, uint8_t sendLen, uint8_t *backData, uint8_t *backLen)
{
  uint8_t status = MI_ERR;
  uint8_t irqEn = 0x00;
  uint8_t waitIRq = 0x00;
  uint8_t lastBits;
  uint8_t n;
  uint16_t i;

  switch (command)
  {
    case PCD_AUTHENT:                //Certification cards close
    {
      irqEn = 0x12;
      waitIRq = 0x10;
      break;
    }
    case PCD_TRANSCEIVE:        //Transmit FIFO data
    {
      irqEn = 0x77;
      waitIRq = 0x30;
      break;
    }
    default:
        break;
  }

  PCD_WriteRegister(ComIEnReg, irqEn|0x80);             //Interrupt request
  ClearBitMask(ComIrqReg, 0x80);                        //Clear all interrupt request bit
  SetBitMask(FIFOLevelReg, 0x80);                       //FlushBuffer=1, FIFO Initialization

  PCD_WriteRegister(CommandReg, PCD_IDLE);              //NO action; Cancel the current command???

  //Writing data to the FIFO
  for (i=0; i<sendLen; i++)
  {
    PCD_WriteRegister(FIFODataReg, sendData[i]);        //tell FIFO to go ready
  }

  //Execute the command
  PCD_WriteRegister(CommandReg, command);           //// transmits data from FIFO buffer to antenna and automatically activates the receiver after transmission
  if (command == PCD_TRANSCEIVE)
  {
    SetBitMask(BitFramingReg, 0x80);                //StartSend=1,transmission of data starts
  }

  //Waiting to receive data to complete
  i = 2000;        //i according to the clock frequency adjustment, the operator M1 card maximum waiting time 25ms???
  do
  {
    //CommIrqReg[7..0]
    //Set1 TxIRq RxIRq IdleIRq HiAlerIRq LoAlertIRq ErrIRq TimerIRq
    n = PCD_ReadRegister(ComIrqReg);
    i--;
  }
  while ((i!=0) && !(n&0x01) && !(n&waitIRq));

  ClearBitMask(BitFramingReg, 0x80);                        //StartSend=0

  if (i != 0)
  {
    if(!(PCD_ReadRegister(ErrorReg) & 0x1B))        //BufferOvflow Collerr CRCErr ProtecolErr
    {
      status = MI_OK;
      if (n & irqEn & 0x01)
      {
        status = MI_NOTAGERR;                        //??
      }

      if (command == PCD_TRANSCEIVE)
      {
        n = PCD_ReadRegister(FIFOLevelReg);             // number of bytes stored in the FIFO buffer
        lastBits = PCD_ReadRegister(ControlReg) & 0x07; //read the first three bits of control register Binary AND Operator copies a bit to the result if it exists in both operands. 
        if (lastBits)
        {
          *backLen = (n-1)*8 + lastBits;
        }
        else
        {
          *backLen = n*8;
        }

        if (n == 0)
        {
          n = 1;
        }
        if (n > MAX_LEN)
        {
          n = MAX_LEN;  //max length is 16
        }

        //Reading the received data in FIFO
        for (i=0; i<n; i++)
        {
          backData[i] = PCD_ReadRegister(FIFODataReg); //what is being returned. up to 16 bits will be stored in return.
        }
      }
    }
    else
    {
      status = MI_ERR;
    }

  }

  //SetBitMask(ControlReg,0x80);           //timer stops
  //Write_MFRC522(CommandReg, PCD_IDLE);

  return status;
}


/*
 * Function Name: MFRC522_Anticoll
 * Description: Anti-collision detection, reading selected card serial number card
 * Input parameters: serNum - returns 4 bytes card serial number, the first 5 bytes for the checksum byte
 * Return value: the successful return MI_OK
 */
uint8_t MFRC522_Anticoll(uint8_t *serNum)
{
  uint8_t status;
  uint8_t i;
  uint8_t serNumCheck=0;
  uint8_t unLen;


  //ClearBitMask(Status2Reg, 0x08);                //TempSensclear
  //ClearBitMask(CollReg,0x80);                    //ValuesAfterColl
  PCD_WriteRegister(BitFramingReg, 0x00);          //TxLastBists = BitFramingReg[2..0] //transmit evething in right fashion

  serNum[0] = PICC_ANTICOLL;
  serNum[1] = 0x20;
  status = MFRC522_ToCard(PCD_TRANSCEIVE, serNum, 2, serNum, &unLen); //redefine status with already stored tag data to recieve back 

  if (status == MI_OK)
  {
    //Check card serial number
    for (i=0; i<4; i++) // checks the third bit of serNum
    {
      serNumCheck ^= serNum[i];             //stores in serNumcheck Bitwise exclusive OR and assignment operator. ie(0 or 0x44=0x44)
    }
    if (serNumCheck != serNum[i])
    {
      status = MI_ERR;
    }
  }

  //SetBitMask(CollReg, 0x80);                //ValuesAfterColl=1

  return status;
}


/*
 * Function Name: CalculateCRC
 * Description: CRC calculation with MF522
 * Input parameters: pIndata - To read the CRC data, len - the data length, pOutData - CRC calculation results
 * Return value: None
 */
void CalculateCRC(uint8_t *pIndata, uint8_t len, uint8_t *pOutData) {
    uint8_t i, n;

    PCD_WriteRegister(CommandReg, PCD_IDLE);             // Ensure the command is in IDLE state
    ClearBitMask(DivIrqReg, 0x04);                       // Clear CRCIrq bit
    SetBitMask(FIFOLevelReg, 0x80);                      // Clear the FIFO pointer

    // Write data to the FIFO
    for (i = 0; i < len; i++) {
        PCD_WriteRegister(FIFODataReg, pIndata[i]);
    }

    PCD_WriteRegister(CommandReg, PCD_CALCCRC);          // Start the CRC calculation

    // Wait for CRC calculation to complete
    i = 0xFF;
    do {
        n = PCD_ReadRegister(DivIrqReg);
        i--;
    } while ((i != 0) && !(n & 0x04));                  // Wait until CRCIrq = 1

    // Read CRC calculation result
    pOutData[0] = PCD_ReadRegister(CRCResultRegL);
    pOutData[1] = PCD_ReadRegister(CRCResultRegM);
}


/*
 * Function Name: MFRC522_SelectTag
 * Description: election card, read the card memory capacity
 * Input parameters: serNum - Incoming card serial number
 * Return value: the successful return of card capacity
 */
uint8_t MFRC522_SelectTag(uint8_t *serNum)
{
  uint8_t i;
  uint8_t status;
  uint8_t size;
  uint8_t recvBits;
  uint8_t buffer[9];

  //ClearBitMask(Status2Reg, 0x08);                        //MFCrypto1On=0

  buffer[0] = PICC_SELECTTAG;
  buffer[1] = 0x70;
  for (i=0; i<5; i++)
  {
    buffer[i+2] = *(serNum+i);
  }
  CalculateCRC(buffer, 7, &buffer[7]);                //??
  status = MFRC522_ToCard(PCD_TRANSCEIVE, buffer, 9, buffer, &recvBits);

  if ((status == MI_OK) && (recvBits == 0x18))
  {
    size = buffer[0];
  }
  else
  {
    size = 0;
  }

  return size;
}



// Function to authenticate with a sector using Key A
uint8_t MFRC522_Authenticate(uint8_t blockAddr, uint8_t *key, uint8_t *serNum) {
    uint8_t status, unLen;
    uint8_t buff[12];
    
    // Prepare the authentication command
//    buff[0] = PCD_AUTHENT;          // Authentication command
    buff[0] = 0x60;                 // Authenticate with Key A
    buff[1] = blockAddr;            // Block address to authenticate
    
    // Copy the key and serial number to the buffer
    for (uint8_t i = 0; i < 6; i++) buff[2 + i] = key[i];
    for (uint8_t i = 0; i < 4; i++) buff[8 + i] = serNum[i];
    
    // Send the command and get the status
    status = MFRC522_ToCard(PCD_AUTHENT, buff, 12, buff, &unLen);
    
    return status;
}

// Function to write 16 bytes of data to a block
// Data is stored in tagTxData[] - 16 bytes
uint8_t MFRC522_WriteBlock(uint8_t blockAddr) {
    uint8_t status;
    uint8_t buff[18];
    uint8_t unLen;

    // Authenticate with the sector containing the block
    status = MFRC522_Authenticate(blockAddr, sectorKey, serNum);
    if (status != MI_OK) {
        return status;  // Return if authentication failed
    }

    // Prepare the write command
    tagTxData[0] = PICC_WRITE;
    tagTxData[1] = blockAddr;
    CalculateCRC(buff, 2, &buff[2]);

    // Send the write command to the card
    status = MFRC522_ToCard(PCD_TRANSCEIVE, buff, 4, buff, &unLen);
    if (status != MI_OK || unLen != 4 || (buff[0] & 0x0F) != 0x0A) {
        return MI_ERR;  // Return if the write command failed
    }

    // Prepare the data to be written
    for (uint8_t i = 0; i < 16; i++) {
        buff[i] = tagTxData[i];
    }

    // Send the data to the card
    status = MFRC522_ToCard(PCD_TRANSCEIVE, buff, 16, buff, &unLen);
    if (status != MI_OK || unLen != 4 || (buff[0] & 0x0F) != 0x0A) {
        return MI_ERR;  // Return if writing the data failed
    }

    return MI_OK;  // Return if the write operation was successful
}

/*
 * Function Name: MFRC522_Read
 * Description: Read block data
 * Input parameters: blockAddr - block address; 
 * received data is stored in tagRxData
 * Return value: the successful return MI_OK
 */
uint8_t MFRC522_Read(uint8_t blockAddr)
{
  uint8_t status;
  uint8_t unLen;

      // Authenticate with the sector containing the block
    status = MFRC522_Authenticate(blockAddr, sectorKey, serNum);
    if (status != MI_OK) {
      return status;  // Return if authentication failed
    }
    
    myDelay(2);

  tagTxData[0] = PICC_READ;
  tagTxData[1] = blockAddr;
  CalculateCRC(tagTxData,2, &tagTxData[2]);
  status = MFRC522_ToCard(PCD_TRANSCEIVE, tagTxData, 4, tagRxData, &unLen);
  tagStatus = status;
  tagByteLength = unLen;
  return status;
}

